"""initial schema

Revision ID: c51bb5646eef
Revises: 
Create Date: 2026-03-28 02:48:42.919754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51bb5646eef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_date', sa.Date(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_income'), type_='unique')
        batch_op.create_unique_constraint('uq_income', ['year', 'month', 'person', 'income_type', 'pay_date'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_constraint('uq_income', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_income'), ['year', 'month', 'person', 'income_type'])
        batch_op.drop_column('pay_date')

    # ### end Alembic commands ###
