"""add debts table

Revision ID: fc124668f054
Revises: c51bb5646eef
Create Date: 2026-03-28 03:40:36.129949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc124668f054'
down_revision: Union[str, Sequence[str], None] = 'c51bb5646eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creditor', sa.String(), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('monthly_payment', sa.Float(), nullable=True),
    sa.Column('monthly_extra', sa.Float(), nullable=True),
    sa.Column('savings', sa.Float(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debts_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debts_id'))

    op.drop_table('debts')
    # ### end Alembic commands ###
